### PR TITLE
Fixes #7

### LINKED ISSUE #7: OhDearWidgetAsset and OhDearAsset does not comply with PSR-4
```
Deprecation Notice: Class webhubworks\ohdear\assetbundles\OhDear\OhDearWidgetAsset located in ./vendor/webhubworks/craft-ohdear/src/assetbundles/ohdear/OhDearWidgetAsset.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class webhubworks\ohdear\assetbundles\OhDear\OhDearAsset located in ./vendor/webhubworks/craft-ohdear/src/assetbundles/ohdear/OhDearAsset.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
```

### PR DESCRIPTION
**Pull request by Saboteur777**

### CODE REVIEW

**Comment by rostockahoi** [comment]
Thank you Ottó

**Comment by Saboteur777** [comment]
Your are welcome!

**Comment by rostockahoi** [comment]
@brandonkelly Thanks for the advice. I regexed the codebase and I can't find any wrong match for `namespace|use(.)*ohdear`. Do you have any specific line or file in mind?

**Comment by brandonkelly** [comment]
@rostockahoi Nevermind, sorry. Looks like all of the `OhDearWidgetAsset` and `OhDearAsset` class references [already](https://github.com/webhubworks/craft-ohdear/search?q=OhDearAsset) [had](https://github.com/webhubworks/craft-ohdear/search?q=OhDearAsset) lowercase `ohdear` namespaces.

**Comment by rostockahoi** [comment]
No problem

**Pull request merged**
